version: '3'
services:
  app:
    build: .
    command: npm start
    volumes:
      - "./src/:/src/"
      - /usr/node_modules
    ports: 
      - "3333:3333"
    depends_on:
     - mysql
    environment:
     - DATABASE_HOST=mysql
  mysql:
    build: ./database